### ISSUE TITLE
key not found

### ISSUE THREAD

**Issue by saucer-man** [Young-Lord/qq-win-db-key#1]
- win10
- qq版本：9.7.3.28.946 
提示一直没找到key：
![image](https://github.com/Young-Lord/qq-win-db-key/assets/32133080/5318e617-db68-4469-9546-ff18518bf7f6)

**Comment by Young-Lord** [comment]
？log都不给？

**Comment by Young-Lord** [comment]
以及确定是在登录前就开始了hook？

**Comment by Young-Lord** [comment]
（说起来第一条评论看错了，抱歉）
以及 干掉 qqprotect 试试
如何永久禁用“QQ安全防护进程(Q盾)”，同时QQ还可以正常启动？ - 知乎用户的回答 - 知乎
https://www.zhihu.com/question/265963430/answer/2492603110

**Comment by saucer-man** [comment]
成功获取到key了，之前是因为我开始hook时已经登录了，没仔细看文档不好意思
