### ISSUE TITLE
佬,数据库能解密,但使用读取信息的那个项目不能读取出明文信息?

### ISSUE THREAD

**Issue by youzi-123** [Young-Lord/qq-win-db-key#2]

**Comment by Young-Lord** [comment]
这个？ https://github.com/Akegarasu/qmsg-unpacker
你改过的代码都不发上来我哪知道啊 再说这个项目本来就不是开箱即用的
msg3.0.db 的话我的另一个项目正在适配 大概~2月后可用

**Comment by Young-Lord** [comment]
这个issue https://github.com/Young-Lord/QQ-History-Backup/issues/6

**Comment by youzi-123** [comment]
不好意思，我没有改代码，我用您的项目解密了数据库后，不太清楚如何用https://github.com/Akegarasu/qmsg-unpacker，这个项目解析出明文，想问一下您当初是如何用这个项目解析出解码后的数据库的？麻烦了。

**Comment by Young-Lord** [comment]
这个基本是拿来实现算法的 也就是说实际用来导出还是别想了
（而且我也没仔细研究 这方面暂时帮不上什么忙）

**Comment by Young-Lord** [comment]
（并不）具体来说，你需要把每个 MsgContent 的内容按它的 example 读取进去，然后它可以转换为 Go 的对象，你接下来可以再手动对这个 Go 对象自己处理

**Comment by youzi-123** [comment]
谢谢解答,那个项目我大致看了一下,我今天在自己试试吧.
