### ISSUE TITLE
MsgContent 字段里的十六进制数据如何解密

### ISSUE THREAD

**Issue by ilihu** [Young-Lord/qq-win-db-key#3]
Msg3.0.db 我已经按照 qq-win-db-key 给的方法解密了。可以用任何sqlite客户端打开。但是 group_123123 这种表里的 MsgContent ，Info 字段里存的都是类似 0x4D53470000000000... 这种经过混淆后的十六进制数据。请教下，这类数据如何解

**Comment by Young-Lord** [comment]
我对这个其实暂时还没有深挖，但我建议你readme里每个链接都看一遍，这个就是tlv格式存储的数据
（要是愿意拿Python实现个解析函数更好

**Comment by Young-Lord** [comment]
https://www.52pojie.cn/thread-1370802-1-1.html

https://github.com/Akegarasu/qmsg-unpacker

**Comment by ilihu** [comment]
好的，感谢！
