### ISSUE TITLE
关于安卓QQ NT版数据库解密

### ISSUE THREAD

**Issue by Eumenides21** [Young-Lord/qq-win-db-key#7]
我在安卓上hook nt_sqlite3_key_v2拿到了一个32位的key，参考这位的方法打开数据库但是并没有成功😥
https://github.com/Young-Lord/QQ-History-Backup/issues/9#issuecomment-1636725067
请问作者有试过打开安卓的数据库吗

**Comment by Young-Lord** [comment]
抱歉并没有

**Comment by Eumenides21** [comment]
> 抱歉并没有
好吧，感谢回复，我再试试其他方法。

**Comment by Eumenides21** [comment]
> 抱歉并没有

好吧，感谢回复，我再试试其他方法。

**Comment by Young-Lord** [comment]
看看 #11 ？
